### ISSUE TITLE
Total GHG(or CO2) budget for country (region)

### ISSUE THREAD

**Issue by Liyang-Guo** [witch-team/RICE50xmodel#3]
Hi,
I am curious to see how WITCH and RICE50+ model can impose constraints on the overall GHG emissions of countries (regions). Of course, I have roughly prepared the estimated emissions data. I would like to simulate energy and economic details under the NDC's near-term and net zero emission targets.
Thank you.

**Comment by Liyang-Guo** [comment]
Or will there be some tutorials on how to configure countries' future emissions?

**Comment by JohannesEmm** [comment]
Hello,

thank you for your interest.
The emissions are of course calibrated in this particular model b ased on emissions insensity sigma(t,n), which you can see in https://github.com/witch-team/RICE50xmodel/blob/main/modules/core_emissions.gms at line 268.
That can easily be adjusted or changed to your needs with some knowledge in GAMS.
Using different policies including NDCs you can see how to use the model in https://github.com/witch-team/RICE50xmodel/blob/main/modules/core_policy.gms using the flags in GAMS (https://www.gams.com/latest/docs/UG_GamsCall.html).

Note however that in general an IAM is a complex mathematical/analytical object, and specific requests for changes or adjustments require quite some time effort and experience.
Due to time constraints we are not able to provide a use-case support, which I am sure you can understand.

Kind regards

J. Emmerling
